"""add_requires_superuser_flag

Revision ID: d6bac3d18831
Revises: e6f331e7cd15
Create Date: 2025-04-27 14:00:34.938242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6bac3d18831'
down_revision = 'e6f331e7cd15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attributes', sa.Column('requires_superuser', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('tags', sa.Column('requires_superuser', sa.Boolean(), server_default='0', nullable=False))
    # SQLite doesn't support ALTER COLUMN for changing types, so we'll skip these
    # The UUID type is already handled correctly in the models
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'requires_superuser')
    op.drop_column('attributes', 'requires_superuser')
    # ### end Alembic commands ###