"""add_tags_and_user_tags_tables

Revision ID: ede46e2d1604
Revises: 99d055ab6fed
Create Date: 2025-04-26 23:03:41.349966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede46e2d1604'
down_revision = '99d055ab6fed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_new_email', table_name='users')
    op.drop_index('ix_users_new_id', table_name='users')
    op.drop_index('ix_users_new_username', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_new_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_new_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_new_email', 'users', ['email'], unique=1)
    # ### end Alembic commands ###